### ISSUE TITLE
Is there a more flowpipe-ish way to do this (TCP server)?

### ISSUE THREAD

**Issue by glanois** [PaulSchweizer/flowpipe#107]
I cooked up a small server example to explore how to implement servers/services in flowpipe.

Here is the code: https://github.com/glanois/flowpipe/blob/dev/examples/flowserver.py

I wanted to encapsulate my TCP server as a `Node` that stood between the network and my application node.  Of course flowpipe did not like two nodes connected together (since that resulted in a circuit - a cyclic graph).  So I have the socket code as a standalone objec that waits for data on the socket, sets the application input, evaluates the graph, and then passes the response from the app to the socket.

What's the right way to do this in flowpipe?

I'll be happy to improve this example with any advice you can provide, and submit it via a pull request to be included with the set of examples.

Thanks.

**Comment by PaulSchweizer** [comment]
Thanks for the contribution @glanois, very much appreciated and sorry for the long delay of an answer. 
This looks correct to me. Flowpipe only aims to provide the benefits of a flow-based design pattern. Such a design pattern is not applicable in all situations. Setting up and running a server is a situation where the flow-based pattern is not really applicable (as you mentioned yourself).

You basically evaluate a graph on the server side which is a perfectly valid use case for flowpipe since the server code might well benefit from the flow-based design but I'm not sure if we need this as an example in the flowpipe repo since it mainly demonstrates how the server is set up. But please correct me if I'm wrong.

I will keep this around though and will mention this use case in the more extensive docs that we want write (and build via sphinx) #17

**Comment by glanois** [comment]
Hi @PaulSchweizer - thanks for your reply.  And thanks for taking a look at my code.  I use this pattern often when interfacing a flow-based application to a bi-directional communications medium (TCP socket, Unix domain socket, serial port, etc).  

Just wanted to mention that flow-based programming allows for cyclic graphs  - see chapter XIV ("Loop-Type Networks") of "Flow Based Programming" by Morrison:  http://www.jpaulmorrison.com/fbp/loop.htm

Maybe some day flowpipe could support this.  For now, I thoroughly enjoy flowpipe as it is in its present form.  

Thanks again.

**Comment by PaulSchweizer** [comment]
Nice read! In the long run we can definitely look into supporting more flow-based paradigms (like this one).  Thanks for the feedback, much appreciated and don't hesitate to come back with more ideas/questions etc.
