### ISSUE TITLE
publish package to pypi

### ISSUE THREAD

**Issue by Anton-4** [PaulSchweizer/flowpipe#38]
It would be convenient to have flowpipe available through pypi.
I have done this recently for another package and would be happy to do this for flowpipe.
I can set it up so publishing is done automatically when a release tag is created on github.

let me know what you think @PaulSchweizer

**Comment by PaulSchweizer** [comment]
@Anton-4 that would be amazing, feel free to go ahead with this. Thank you very much!

**Comment by Anton-4** [comment]
You're welcome :) I will probably get this done later this week.

**Comment by Anton-4** [comment]
@PaulSchweizer can you add a new release/tag on github to test it out?

**Comment by Anton-4** [comment]
@PaulSchweizer Thanks, the version number is 0.1.0 because that's what's in the `setup.py`
should I submit a pull request setting it to 0.4.5? That way it is synced up with the github releases.
I will also add that you can now just `pip install flowpipe` to the readme.

**Comment by PaulSchweizer** [comment]
Yep, that would be great! Also, travis failed: https://travis-ci.org/PaulSchweizer/flowpipe/builds/478269908?utm_medium=notification&utm_source=email
This is because it is trying to deploy for every py version, is it easy to set it up so it only deploys once? Or omit the deployment if is already deployed. Thanks again for your help!

**Comment by Anton-4** [comment]
I will check it out.

**Comment by PaulSchweizer** [comment]
Thanks @Anton-4 good point: https://pypi.org/user/PaulSchweizer/
