### ISSUE TITLE
How should subgraphs work

### ISSUE THREAD

**Issue by PaulSchweizer** [PaulSchweizer/flowpipe#84]
Currently there is no support for sub-graphs, although I found this, which I think makes no sense at all 😄: https://github.com/PaulSchweizer/flowpipe/blob/master/flowpipe/graph.py#L48

Let's gather some ideas/thoughts on how sub graphs should work.

**Comment by neuneck** [comment]
My suggestion is to have the Graph itself duck type an INode:

- Its inputs are all open InputPlugs of nodes in the subgraph
- Its outputs are all open OutputPlugs of nodes in the subgraph
- It is considered dirty as soon as any node in the subgraph is dirty
- The main function to execute is already named consistently.

This way, substitution a set of connected nodes in the graph by the subgraph they span works well with the intuition of replacing that set of nodes with a meta-node, if you will.

**Comment by Onandon11** [comment]
Like I said earlier, we are very frequently using sub graph's. Whereas a sub graph is specific combination of nodes.

Currently were transform a function which creates a graph internally to an `INode`, like in the example below.
```python
@Node(outputs=['bar'])
def foo(a, node_name: str = 'Sub graph'):
    graph = Graph(name=node_name)
    f1 = baz1(graph=graph, name='Baz 1', a=a)
    f2 = baz2(graph=graph, name='Baz 2')

    f1.outputs['b'] >> f2.inputs['a']

    graph.evaluate()
    bar = f2.outputs['b'].value
    return {'bar': bar}

if __name__ == "__main__":
    graph = Graph(name='Graph with sub graphs')
    f1 = function(graph=graph, name='Other function', a=1)
    f2 = foo(graph=graph, name='Foo 1')

    f1.outputs['bar'] >> f2.inputs['a']
    print(graph)
```
It's only too bad that we can't see the contents of the sub graph, other than executing the graph. In other words. It would be great that connecting graph with another, automatically merges the execution order and printing the sub graph of function "Foo 2" below.

```
+-------------------------+          +-------------------------+
|    Other function       |          |          Foo 2          |
|-------------------------|          |-------------------------|
o a<1>                    |     +--->o a<>                     |
|                         |     |    o node_name<"Sub graph>   |
|                     bar o-----+    |                     bar o
+-------------------------+          +-------------------------+
```
In addition to @neuneck, I think it should be the other way around. So an `INode` should duck type a `Graph`. Because in essence an sub graph is not very different than a node, it only contains more nodes.

**Comment by neuneck** [comment]
@Onandon11 I aggree, a `Graph` is basically a `Node`, so a `Graph` should mimic the behavior of a `Node`. To me it does not really make sense to introduce an evaluation order and threaded/multiprocessed evaluation to every Node, but instead to add inputs, outputs and a `is_dirty` property to a Graph.

Basically, I want to be able to use a `Graph` just like a `Node`, so `Graph` has to duck type `Node`.

I like the idea of the graph inside a node a lot, from a practical perspective! I will use the Node that sets up a graph for my own project for now :) Thank for the inspiration!

**Comment by PaulSchweizer** [comment]
Good news, I think sub graphs already work kind of the way they should, we just need to fix a few things.
(I had totally forgotten that this was in there already, sorry)

## Currently

```python
from flowpipe.node import Node
from flowpipe.graph import Graph

@Node(outputs=['out'])
def MyNode(self, in1):
    print(self.name)
    return {'out': None}


sub = Graph(name='sub')
sub_n1 = MyNode(graph=sub, name='Sub1')
sub_n2 = MyNode(graph=sub, name='Sub2')
sub_n1.outputs['out'] >> sub_n2.inputs['in1']

print(sub)
```

The sub graph looks like this:

```
+-----------+          +-----------+
|   Sub1    |          |   Sub2    |
|-----------|          |-----------|
o in1<>     |     +--->o in1<>     |
|       out o-----+    |       out o
+-----------+          +-----------+
```

Now we can create another graph that utilizes the sub graph by connecting directly to its nodes.
Please note that the

```python
main = Graph(name='main')

main_n1 = MyNode(graph=main, name='Main1')
main_n2 = MyNode(graph=main, name='Main2')
main_n3 = MyNode(graph=main, name='Main3')

main['Main1'].outputs['out'] >> sub['Sub1'].inputs['in1']
sub['Sub2'].outputs['out'] >> main['Main2'].inputs['in1']
sub['Sub2'].outputs['out'] >> main['Main3'].inputs['in1']

print(main)
main.evaluate()
```

```
+------------+          +-----------+          +-----------+          +------------+
|   Main1    |          |   Sub1    |          |   Sub2    |          |   Main2    |
|------------|          |-----------|          |-----------|          |------------|
o in1<>      |     +--->o in1<>     |       -->o in1<>     |       -->o in1<>      |
|        out o-----+    |       out o---       |       out o---       |        out o
+------------+          +-----------+          +-----------+          +------------+
                                                                      +------------+
                                                                      |   Main3    |
                                                                      |------------|
                                                                   -->o in1<>      |
                                                                      |        out o
                                                                      +------------+

Main1
Sub1
Sub2
Main2
Main3
```

The connections are not drawn correctly but the sub graph is being expanded and also evaluated correctly.

## Adjustments

How do we want to handle the plugs?

### Option 1 - The current behaviour

Because the nodes on a graph can be accessed directly, they can also be connected directly to nodes of another graph, therefore adding all nodes of that "subgraph" to the other graph.
The issue to fix here would be to make sure that ALL nodes are taken into account from the sub graph, this is currently NOT the case! Together with fixing the str representation, this looks like it'd just be two bugs to fix.

### Option 2 - Expose plugs on the graph

Another option would be to only explicitely expose certain plugs of nodes of a graph and then connect to these when using the sub graph, something like this:

```python

class MyGraph(Graph):

    def __init__(self):
        sub_n1 = MyNode(graph=self, name='Sub1')
        sub_n2 = MyNode(graph=self, name='Sub2')

        self.inputs['graph_input'] = sub_n1.inputs['in1']
        self.outputs['graph_output'] = sub_n2.outputs['in1']


sub = MyGraph(name='sub')
main = Graph(name='main')
main_n1 = MyNode(graph=main, name='Main1')

main_n1.outputs['out'] >> sub.inputs['graph_input']
```

The evaluation result would be the same as in option 1, we expand all graphs into one.
The difference would be that the ins and outs of the graph would (have to) be authored during development.

The graph would then probably be a sub-class of INode and we'd probably have to make some more adjustments to the plug classes (have not looked a that in detail though).

In any case we also have to work on docs for this.

Happy to hear your further thoughts on this.

**Comment by neuneck** [comment]
I am not sure if the graph in/outputs have to be authored during development. A subgraph input/output could just be any plug inside of the subgraph that does not have a connection yet. 

If a user wants a more elaborate scheme, where he exposes plugs that are also used internally in the subgraph, he has to access those plugs explicitly, but to me that's where we start crossing the border of a set of nodes being considered a subgraph. 

So my suggestion would be to add something along the lines of:
```
class Graph(object):
    ....
    @property
    def inputs(self):
        iplugs = []
        for node in self.nodes:
            for iplug in node.inputs:
                if not iplug.connections:
                    iplugs.append(iplug)
```
and the same for outputs.

**Comment by neuneck** [comment]
I briefly looked at making this definition of graph inputs / outputs a proper feature, but `SubPlugs` are tricky:

What should be the behavior if some SubPlugs have a connection and others don't? Can the list of Graph-level inputs / outputs have a mix of Plugs and SubPlugs?

Off the top of my head, this makes sense. For both, InputPlugs and SubInputPlugs I can set their `value` property. They still remain attached to their original nodes, since the Graph's inputs are basically just a view on the unconnected plugs in the graph.
Since I don't work with SubPlugs in my projects, I would like to hear a comment from somebody who uses them if a mix of Plugs and SubPlugs as `Graph.inputs` makes sense.

Tthe above reasoning applies to OutputPlugs / SubOutputPlugs as well.

**Comment by Onandon11** [comment]
Sorry for the late response but I had some busy times. Nevertheless, great that such a functionality is there already.

I think **Option 1** is the better one. I agree with @neuneck that someone may connect to any plug in the subgraph. This give more flexibility for the user and less constrains in coding style. I must say I always create the nodes trough the `@Node` decorator. Therefore it will be harder to add exposure functionality to the function. 

Using the `@Node` also gives a problem that you can't (or not pythonically) introspect into the function (although it's a `INode` class). So you cannot connect before runtime because when the subgraph changes it's name or something the whole flow will break.

I imagine some thing like the following. So creating some sort of `SubGraph` object which not passes values, but more handles to inputs and outputs.
```python
@Subgraph(outputs=['output_plug'])
def SubGraph(input_plug):
    sub = Graph(name='sub') 
    sub_n1 = MyNode(graph=sub, name='Sub1')
    sub_n2 = MyNode(graph=sub, name='Sub2')

    # Notice the direction connection of the input variable to the node
    input_plug >> sub_n1.inputs['in1']
    sub_n1.outputs['out'] >> sub_n2.inputs['in1']
    output_plug = sub_n2.outputs['out']
    # Not sure how to do this, but I imagine the output to be a plug
    return output_plug

```

**Comment by neuneck** [comment]
How do we want to handle cases where the names (of plugs or nodes) are not unique?

While it makes sense to enforce node name uniqueness across a flat graph, if we allow subgraphs (and by extension, nested subgraphs), it can become quite involved to ensure name uniqueness across the overall resulting graph. Especially in situations where the overall graph would contain multiple instances of a given subgraph it would be neat to handle naming collisions with something less severe than an error.

The same issue concerns Plugs, too - forcing name uniqueness on plugs on the graph level would be very unexpected for me as a user, and pretty inconvenient in a lot of circumstances. If we are to assemble the inputs/outputs of a (sub)Graph from the unconnected plugs inside, we need to handle naming collisions again.

There are multiple options I see:

1. We _do_ enforce name uniqueness of nodes, even across subgraphs and change the name of Plugs to the schema `node_name.plug_name` similar to how we handle subplugs. The obvious advantage is that it is the minimal change and employs a naming scheme that's already in use. On the other hand, for subplugs the scheme would then be `node_name.plug_name.subplug_name` already.
2. We don't enforce name uniqueness of nodes in imported subgraphs and dynamically rename them `subgraph_name.node_name`. This makes the issue in solution 1 even worse, worst case my graph has an input `subgraph_name.node_name.plug_name.subplug_name` and I need to know the full history of the graph in order to find the input I want - which means I gained nothing in terms of API clarity and brevity.
3. In the keras api for deep learning, this issue is solved by dynamically appending `_2`, `_3` ... to subsequent layers of the same name, unless the name of the layer has been set manually. We could do something similar if the node name derives from it's class name and was not set manually. This way, if someone wants to name nodes, he has to take care of uniqueness - if one doesn't care about the names, the default handles arbitrary nestings well, but makes inspection of the graph harder. The same could work for plugs on the graph level.

I am not super happy with any of those suggestions - maybe we can come up with something better together?

**Comment by PaulSchweizer** [comment]
Thanks for the discussion and the good points that were raised.

# Accessing nodes on sub graphs

The problem with name-uniqueness across all nodes and all subgraphs is a nasty one and none of the solutions are ideal, as @neuneck pointed out. 

I think however that we can avoid having to deal with it by just NOT making it possible to access all nodes of all subgraphs via `__getitem__` on the graph and keep this way of accessing limited only to a graph's own nodes. 

Instead, users have to "index" their way through down the levels of the nested graph and we only need to keep the names unique on each level (which we already do anyways).

Consider this graph with three levels of nested subgraphs:

```python
@Node(outputs=["out"])
def MyNode(in_):
    return {"out": in_}

main = Graph("main")
main_node = MyNode(graph=main)

parent = main
for i in range(3):
    sub = Graph("sub")
    sub_node_1 = MyNode(graph=sub)
    parent["MyNode"].outputs["out"] >> sub["MyNode"].inputs["in_"]
    parent = sub
```

It prints like this:

```
+------------+          +------------+          +------------+          +------------+
|   MyNode   |          |   MyNode   |          |   MyNode   |          |   MyNode   |
|------------|          |------------|          |------------|          |------------|
o in_<>      |     +--->o in_<>      |     +--->o in_<>      |     +--->o in_<>      |
|        out o-----+    |        out o-----+    |        out o-----+    |        out o
+------------+          +------------+          +------------+          +------------+
```

Accessing the nodes of the main graph will be unchanged, it does not list any of the subgraph nodes. Instead we introduce a `Graph.subgraphs` property that lists all subgraphs:

```python
assert len(main.nodes) == 1 
assert len(main.subgraphs) == 1
assert len(main.subgraphs["sub"].subgraphs) == 1
```

With that subgraph property, it would then be possible to access all nodes without naming clashes. 

```python 
level_0_mynode = main["MyNode"]
level_1_mynode = main.subgraphs["sub"]["MyNode"]
level_2_mynode = main.subgraphs["sub"].subgraphs["sub"]["MyNode"]
level_3_mynode = main.subgraphs["sub"].subgraphs["sub"].subgraphs["sub"]["MyNode"]
```

The tricky part here will be to keep the names of the subgraphs unique as there is no explicit way of adding a subgraph to the parent graph. Instead the subgraphs are the collection of the graphs of the connected nodes. But it is still possible, just a bit more work. 

Also, `INode` then has to have a `graph` property that holds a reference to its graph in order to be able to assemble all this information correctly.

## Expand graph

For evaluation and visualizing we have a process that expands the entire graph into one flat graph. At this internal level, name-uniqueness is not a problem since we're dealing with objects. The only thing would be log messages and the visualization where we might want to include the graph name in the message to make things clearer, so the above graph should maybe print something more like this:

```
+------------+          +------------+          +----------------+          +--------------------+
|   MyNode   |          | sub.MyNode |          | sub.sub.MyNode |          | sub.sub.sub.MyNode |
|------------|          |------------|          |----------------|          |--------------------|
o in_<>      |     +--->o in_<>      |     +--->o in_<>          |     +--->o in_<>              |
|        out o-----+    |        out o-----+    |            out o-----+    |                out o
+------------+          +------------+          +----------------+          +--------------------+
```

# Accessing Plugs on Graphs

I think we shouldn't expose the non-connected plugs of the nodes on the graph as this causes all sorts of headaches regarding the naming (as discussed).    

Instead, we should offer two ways of how to deal with plugs:

## Direct access to plugs

If we go with the above model on Nodes, Plugs could be accessed and connected directly like this:

```python 
level_1_mynode_in_plug = main.subgraphs["sub"]["MyNode"].inputs["in_"]
```

The only issue here is that this can become a bit combersome and long (but constructing a deeply nested network is cumbersome by definition ...)
A simple solution for this concern would be to just employ custom logic when assembling a big nested graph and store references to nodes and graphs in a way that makes more sense in the specific use case, so nothing we should or could worry about.

## Manually Authored Plugs

Another solution would be to author graphs in a more user-friendly way by explicitly promoting `node plugs` to `graph plugs` to communicate which plugs should be used when working with the graph and which ones should be left untouched. This is just a convention though, direct access is still possible.

On the graph level, plug names have to be unique again, so if the graph contains two nodes with identical plug names that should both be promoted, the user just has to define new names:

```python 
# Promote the plug to the graph
main["MyNode"].inputs["in_"].promote(name="input_to_graph")  # Optionally define a new name, otherwise the original name is used

assert main.inputs["input_to_graph"] is main["MyNode"].inputs["in_"]

top = Graph("top")
top_node = MyNode(graph=top)

top_node.outputs["out"] >> main.inputs["input_to_graph"]
```

This would make the Graph behave like a Node.

## Subplugs

I think there should be no extra problems regarding the behaviour of subplugs, but I have to revisit that at a later stage to make sure.

Let me know if any of this does not make sense.

I hope I can put some code for this online soon.

**Comment by Onandon11** [comment]
Every time I read you suggestions I'm wondering how do you find the time to create such extensive examples 😄 

Personally I would like to prefer the "Manually Authored Plugs", so promoting inputs to be graph inputs. I think it's also the most pythonic and readable solution. It's also quite clear what the developer wants without running the code. This is also handy later on for logging, type hinting and visualization. This gives the user the freedom to `promote` Plugs at compile time, but at run-time the Plugs remain static (from a connection point of view)...

What do we need to do to get this working? I want create kind of a timeline (see #98) and this could/should be incorporated in this planning I think.

**Comment by neuneck** [comment]
Seconded! I like the `promotion` idea.

What about making subgraphs visible with the `__getitem__` magic? Then the line between a subgraph and a node vanishes api-wise. Granted, if you nest Graphs of the same name, you get weird stuff like
```
graph["sub"]["sub"]["sub"]["sub"]["MyNode"]
```
but if you have meaningfully named subgraphs, something like
```
graph["FaceMatching"]["FaceDetection"].inputs["image"]
```
reads quite nicely.

**Comment by Onandon11** [comment]
I think we don't have to worry that much about nested subgraphs. It's good to have it in mind, but users can always abuse the python syntax if they like. If I look to my own usage of flowpipe, I would like to connect from the main graph maybe one level deeper, not more than that. That subgraph thereafter creates their own connections to other subgraphs. So syntax wise I'm not that worried about `graph["sub"]["sub"]["sub"]["sub"]["MyNode"]`.
